services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
#      Custom data path for postgres. The default path is /var/lib/postgresql.
      PGDATA: /data/postgres
    volumes:
      - postgres:/data/postgres
    ports:
      - "5433:5432"
    networks:
      - postgres
    restart: unless-stopped

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
#      Default path
    volumes:
      - pgadmin:/var/lib/pgadmin
    ports:
      - "8001:80"
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge


volumes:
  postgres:
  pgadmin:


# Steps to connect to the postgres Database:
# 1. Using the local pgAdmin app installed on you machine:
#   -> Open the App
#   -> Click on Register --> Server
#   -> In the General Tab, enter the name.
#   -> In the connection tab enter Host: 'localhost', port:'5433', username and password as mentioned
#   -> Click on Save

# 2. Using the pgAdmin app on the port specified in the docker service (Here, 8001):
#   -> Open localhost:8001
#   -> Click on Register --> Server
#   -> In the General Tab, enter the name.
#   -> In the connection tab enter Host: 'postgres', port:'5432', username and password as mentioned.
# Note: In this case, you use port 5432 (the internal port), not 5433 as both the services are running on the same
#       network and can talk to each other using the original ports that are running on.
#   -> Click on Save


#services:
#  mysql:
#    container_name: mysql_container
#    image: mysql
#    environment:
#      MYSQL_ROOT_PASSWORD: devansh
#      MYSQL_DATABASE: devansh
#      MYSQL_USER: devansh
#      MYSQL_PASSWORD: devansh
#
#    volumes:
#      - mysql_data:/var/lib/mysql
#
#    ports:
#      - "3307:3306"
#
#    networks:
#      - mysql
#    restart: unless-stopped
#
#  phpmyadmin:
#    container_name: phpmyadmin_container
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: mysql
#      PMA_PORT: 3306
#      MYSQL_ROOT_PASSWORD: devansh
#
#    ports:
#      - "8484:80"
#    networks:
#      - mysql
#    restart: unless-stopped
#
#networks:
#  mysql:
#    driver: bridge
#
#volumes:
#  mysql_data:
